const config = require("../lib/config")();
const { NOTIFICATION_URL, PAYMENT_URL, USER_URL, AUTH_URL } =
  config.SERVICE_URLS;

module.exports = {
  USER_TYPE: {
    SUPER_ADMIN: "SUPER_ADMIN",
    STAFF_MEMBER: "STAFF_MEMBER",
    FIELD_AGENT: "FIELD_AGENT",
    CITIZEN: "CITIZEN",
  },
  COMMON_HEADERS: {
    headers: {
      "accept-version": "1.0.0",
    },
  },
  QUEUE: {
    PDSL_NOTIFICATION_QUEUE: config.QUEUE.NOTIFICATION_QUEUE,
    PDSL_AUDIT_QUEUE: config.QUEUE.AUDIT_QUEUE,
    NOTIFICATION_LOG_QUEUE: config.QUEUE.NOTIFICATION_LOG_QUEUE,
  },
  PERMIT_STATUS: {
    PENDING: "PENDING",
    ACTIVE: "ACTIVE",
    EXPIRED: "EXPIRED",
    IN_ACTIVE: "IN_ACTIVE",
  },
  FINANCIAL_YEAR: {
    CURRENT: "CURRENT",
    NEXT: "NEXT",
  },
  PAYMENT_MODES: {
    MPESSA_EXPRESS: "MPESSA_EXPRESS",
    USSD: "USSD",
    MPESSA: "MPESSA",
    KCB: "KCB",
  },
  BASE_URLS: {
    NOTIFICATION_BASE_URL: NOTIFICATION_URL,
    PAYMENT_SERVICE_BASE_URL: PAYMENT_URL,
    AUTH_SERVICE_BASE_URL: AUTH_URL,
    USER_SERVICE_BASE_URL: USER_URL,
  },
  AUDIT_CONSTANTS: {
    UNIVERSAL: "UNIVERSAL_BILLING",
    LICENSE_PERMIT: "LICENSE_PERMIT",
    PUBLIC_HEALTH: "PUBLIC_HEALTH",
  },
  PAGE: {
    LIMIT: 20,
  },
  APPLICATION_STATUS: {
    SUBMITTED: "SUBMITTED",
    IN_PROCESS: "IN-PROCESS",
    REJECTED: "REJECTED",
    APPROVED: "APPROVED",
    DRAFT: "DRAFT",
    QUERY_RAISED: "QUERY_RAISED",
  },
  PAYMENT_STATUS: {
    PAID: "PAID",
    FAIL: "FAIL",
    NOT_PAID: "NOT_PAID",
    PENDING: "PENDING",
    CANCELLED: "CANCELLED",
  },
  TEMPLATE_ID: {
    DOCUMENT_REQUEST_TEMPLATE_ID: "d-cc7ff252832b4658bc7eaf4269e3e351",
  },
  DOCUMENT_REQUEST_TYPE: {
    REUPLOAD: "REUPLOAD",
    ADDITIONAL: "ADDITIONAL",
  },
  NOTIFICATION_TYPE: {
    READ: "READ",
    UNREAD: "UNREAD",
  },
  INSPECTION_STATUS: {
    APPROVED: "APPROVED",
    REJECTED: "REJECTED",
    ALL: "ALL",
    ACTIVE: "ACTIVE",
  },
  SERVICES: {
    LIQUOR: "LIQUOR",
    ADVERTISEMENT: "ADVERTISEMENT",
    LAND_AND_PROPERTIES: "LAND_AND_PROPERTIES",
    OTHER_LICENSE: "OTHER_LICENSE",
    LAND_RENT_AND_RATES: "LAND_RENT_AND_RATES",
    MEDICAL_CERTIFICATE: "MEDICAL_CERTIFICATE",
    FOOD_HYGIENE: "FOOD_HYGIENE",
    OCCUPATIONAL_CERTIFICATE: "OCCUPATIONAL_CERTIFICATE",
    BUILDING_APPROVAL: "BUILDING_APPROVAL"
  },
  SERVICE_MODULE: {
    LICENSE_PERMIT: "LICENSE_PERMIT",
    LAND_RENT_AND_RATES: "LAND_RENT_AND_RATES",
    PUBLIC_HEALTH: "PUBLIC_HEALTH",
  },
  DURATION: {
    MONTHLY: 'MONTHLY', 
    QUARTERLY: 'QUARTERLY', 
    HALF_YEARLY: 'HALF_YEARLY', 
    ANNUAL: 'ANNUAL'
  },
  TYPE: {
    SELF: 'self', 
    CLIENT: 'client'
  },
  LICENSE_PERMIT_STATUS: {
    VALID: "VALID",
    IN_VALID: "IN_VALID",
  },
  LAND_STATUS: {
    ACTIVE: "ACTIVE",
    SUBDIVIDED: "SUBDIVIDED",
    TRANSFERRED: "TRANSFERRED",
    DISPUTED: "DISPUTED",
    PENDING: "PENDING",
  },
  LAND_USE_TYPES: {
    RESIDENTIAL: "RESIDENTIAL",
    COMMERCIAL: "COMMERCIAL",
    AGRICULTURAL: "AGRICULTURAL",
    INDUSTRIAL: "INDUSTRIAL",
    RECREATIONAL: "RECREATIONAL",
    TRANSPORTATION: "TRANSPORTATION",
    INSTITUTIONAL: "INSTITUTIONAL",
    CONSERVATION: "CONSERVATION",
  },
  LAND_SUB_TYPE: {
    NEW_LAND: "NEW_LAND",
    LAND_SUBDIVISION: "LAND_SUBDIVISION",
    LAND_USE_CHANGE: "LAND_USE_CHANGE",
    SUBDIVISION_PLOT: "SUBDIVISION_PLOT",
  },
  LAND_CATEGORY: {
    LAND_MANAGEMENT: "LAND_MANAGEMENT",
  },
  LAND_ZONES: {
    HIGH_DENSITY_RESIDENTIAL: "HIGH_DENSITY_RESIDENTIAL",
    LOW_DENSITY_RESIDENTIAL: "LOW_DENSITY_RESIDENTIAL",
    PERI_URBAN_RESIDENTIAL: "PERI_URBAN_RESIDENTIAL",
    RURAL_SMALLHOLDER: "RURAL_SMALLHOLDER",
  },

  LAND_ZONE_CODES: {
    HIGH_DENSITY_RESIDENTIAL: "ZONE_A",
    LOW_DENSITY_RESIDENTIAL: "ZONE_B",
    PERI_URBAN_RESIDENTIAL: "ZONE_C",
    RURAL_SMALLHOLDER: "ZONE_E",
  },
  PATH_CODES: {
    PATH_A: "PATH_A",
    PATH_B: "PATH_B",
  },

  PATH_CODE_NAMES: {
    PATH_A: "VALUATION_ROLL",
    PATH_B: "GAZETTE_NOTICE",
  },
  RATE_UNITS: {
    KES_PER_ACRE: "KES_PER_ACRE",
    KES_PER_M2: "KES_PER_M2",
    PERCENT: "PERCENT",
  },
};
