exports.validationConstants = {
    STRING_MIN_LENGTH:3,
    STRING_MAX_LENGTH:55,
    POSTAL_CODE_LENGTH:5,
    PHONE_NUMBER_MIN_LENGTH:9,
    PHONE_NUMBER_MAX_LENGTH:13,
    PASSWORD_MIN_LENGTH:6,
    PASSWORD_MAX_LENGTH:15,
};